name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: MSVC Debug
            mode: Debug
            cc: cl
          - name: MSVC Release
            mode: Release
            cc: cl
          - name: Clang Debug
            mode: Debug
            cc: clang-cl
          - name: Clang Release
            mode: Release
            cc: clang-cl

        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build
      run: |
        $devShell = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
        $installPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
        Import-Module $devShell
        Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"
        $env:CC = ${{ matrix.config.cc }}
        $env:CXX = ${{ matrix.config.cc }}
        cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
        cmake --build build --target utl-test

    - name: Run tests
      run: build\utl-test.exe
